### ISSUE TITLE
Failed to construct nozzle consumer: Failed To Fetch Token

### ISSUE THREAD

**Issue by webbbret** [rakutentech/kafka-firehose-nozzle#26]
I have confirmed that the username and password in the toml file will authenticate against the UAA endpoint, however, I am getting the following errors

`[ERROR] Failed to construct nozzle consumer: failed to fetch token: Received a status code 401 Unauthorized`

Followed by: 

`2019-01-02T17:26:53.628-08:00 [APP/PROC/WEB/2] [OUT] Exit status 2
2019-01-02T17:26:53.631-08:00 [CELL/SSHD/2] [OUT] Exit status 0`

Note that I have Username and Password in the .toml file and do not have UAA_PASSWORD in the manifest. I have tried adding to manifest, but got the same results. Is there something I am not configuring correctly? Many thanks in advance for your help.

**Comment by giner** [comment]
nozzle client has to be given doppler.firehose authority, e.g.
```
uaa:
  clients:
...
    kafka-nozzle:
      authorities: oauth.login,doppler.firehose
      authorized-grant-types: client_credentials
      override: true
      secret: SUPERSECRET
...
```
